# Generated by Django 4.0.5 on 2022-06-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malombacodes_app', '0002_malombacodes_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='malombacodes_profile',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
