# Generated by Django 4.0.5 on 2022-06-24 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('malombacodes_app', '0003_malombacodes_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malombacodes_post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
