# Generated by Django 4.0.5 on 2022-06-25 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('malombacodes_app', '0005_rename_post_url_malombacodes_post_site_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malombacodes_post',
            name='notes',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='malombacodes_post',
            name='post_description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Memes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meme_title', models.CharField(max_length=100)),
                ('meme_description', models.TextField(max_length=100)),
                ('meme_image', models.ImageField(upload_to='memes/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
